name: Build and Push Laravel Sail Docker Image

on:
  push:
    branches:
      - main

jobs:
  sail-build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7-din

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up PHP with Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: |
          composer install
          ./vendor/bin/sail up -d
        env:
          COMPOSER_NO_INTERACTION: 1

      - name: Authenticate with Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Sail Image
        run: |
          ./vendor/bin/sail build --no-cache

      - name: Tag and Push Docker Image
        run: |
          docker tag laravel.test ${{ secrets.DOCKERHUB_USERNAME }}/your-laravel-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/your-laravel-app:latest
